### ISSUE TITLE
跟着文档操作了下，发现无法正常运行train！

### ISSUE THREAD

**Issue by davaram** [buriedms/Old2Life-Paddle#1]
CustomDatasetDataLoader
dataset [UnPairOldPhotos_SR] was created
start load bigfile (0.00 GB) into memory
find total 81 images
load 0 images done
load all 81 images done
start load bigfile (0.01 GB) into memory
find total 8 images
load 0 images done
load all 8 images done
start load bigfile (2.09 GB) into memory
find total 27088 images
load 0 images done
load 5000 images done
load 10000 images done
load 15000 images done
load 20000 images done
Traceback (most recent call last):
  File "/home/ubuntu/download/Old2Life-Paddle/Global/train_domain_A.py", line 23, in <module>
    data_loader = CreateDataLoader(opt)
  File "/home/ubuntu/download/Old2Life-Paddle/Global/data/data_loader.py", line 5, in CreateDataLoader
    data_loader.initialize(opt)
  File "/home/ubuntu/download/Old2Life-Paddle/Global/data/custom_dataset_data_loader.py", line 27, in initialize
    self.dataset = CreateDataset(opt)
  File "/home/ubuntu/download/Old2Life-Paddle/Global/data/custom_dataset_data_loader.py", line 17, in CreateDataset
    dataset.initialize(opt)
  File "/home/ubuntu/download/Old2Life-Paddle/Global/data/online_dataset_for_old_photos.py", line 184, in initialize
    self.loaded_imgs_clean = BigFileMemoryLoader(self.load_img_dir_clean)
  File "/home/ubuntu/download/Old2Life-Paddle/Global/data/Load_Bigfile.py", line 27, in __init__
    self.__load_bigfile()
  File "/home/ubuntu/download/Old2Life-Paddle/Global/data/Load_Bigfile.py", line 15, in __load_bigfile
    img_name_len = struct.unpack('i', fid.read(4))[0]
struct.error: unpack requires a buffer of 4 bytes

**Comment by buriedms** [comment]
这个应该是数据加载部分的问题，我当时运行的时候没有遇到过这样的问题，建议可以在网上搜索一下解决方法，很抱歉没有帮到你
